all:
  vars:
    ansible_ssh_user: root
    ansible_python_interpreter: /usr/bin/python3
    
    kube_api: "10.10.20.30"
    kube_api_port: "6443"
    kube_pod_net_calico: "10.11.0.0/16"
    kube_version: "1.24.7-00"
    kube_weave_version: "v2.8.1"

    etcd_port: "2380"
    etcd_client: "2379"
    
  children:
    k8s-master:
      hosts:
        kmaster1:
        kmaster2:
    k8s-worker:
      hosts:
        kworker1:
    ha-proxy:
      vars:
        docker_version: "alpine3.16"
        vip_address: "{{ kube_api }}"
        keepalived_vrrp_instances:
          state: "MASTER"
          priority: "100"
          virtual_router_id: "15"
          interface: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['alias'] }}"

          authentication:
            auth_type: "PASS"
            auth_pass: "12345678"
      hosts:
        etcd-1:
        etcd-2:          
        etcd3:
    etcd:
      vars:
        virsion: "3.5.3"
        token: etcd-cluster-1
      hosts:
        etcd-1:
        etcd-2:
        etcd3:

    