- name: cluster init 
  shell: kubeadm init --config /etc/kubernetes/config.yaml

# добавляем переменную для root, чтобы можно было выполнять kubectl
- name: add variables in /root/.bashrc
  lineinfile:
    path: "/root/.bashrc"
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"

- name: read new root variables
  shell:
    cmd: source ~/.bashrc
    executable: /bin/bash

- name: deploy a pod network to the cluster
  shell:
    cmd: /usr/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/weaveworks/weave/releases/download/{{kube_weave_version}}/weave-daemonset-k8s.yaml
    chdir: /etc/kubernetes/