---
- name: get kubectl version
  shell:
    cmd: kubectl version | base64 | tr -d '\n' 
  register: kubectl_version

- name: deploy a pod network to the cluster
  shell:
    cmd: /usr/bin/kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout }}"
    chdir: /etc/kubernetes/