---
- name: get kubectl version
  shell:
    cmd: kubectl version | base64 | tr -d '\n' 
  register: kubectl_version

- name: deploy a pod network to the cluster
  shell:
    cmd: /usr/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/weaveworks/weave/releases/download/{{kube_weave_version}}/weave-daemonset-k8s.yaml
    chdir: /etc/kubernetes/